from src.database import Database

stocks = [
    # Technology
    ("AAPL", "Apple", "Technology"),
    ("MSFT", "Microsoft", "Technology"),
    ("GOOGL", "Alphabet", "Technology"),
    ("AMZN", "Amazon", "Technology"),
    ("NVDA", "NVIDIA", "Technology"),
    ("META", "Meta", "Technology"),
    ("TSLA", "Tesla", "Technology"),
    ("AVGO", "Broadcom", "Technology"),
    ("ORCL", "Oracle", "Technology"),
    ("CSCO", "Cisco", "Technology"),
    ("INTC", "Intel", "Technology"),
    ("AMD", "AMD", "Technology"),
    ("ADBE", "Adobe", "Technology"),
    ("CRM", "Salesforce", "Technology"),
    ("QCOM", "Qualcomm", "Technology"),
    ("TXN", "Texas Instruments", "Technology"),
    ("IBM", "IBM", "Technology"),
    ("NOW", "ServiceNow", "Technology"),
    ("INTU", "Intuit", "Technology"),
    ("AMAT", "Applied Materials", "Technology"),
    # Finance
    ("JPM", "JPMorgan Chase", "Finance"),
    ("BAC", "Bank of America", "Finance"),
    ("WFC", "Wells Fargo", "Finance"),
    ("GS", "Goldman Sachs", "Finance"),
    ("MS", "Morgan Stanley", "Finance"),
    ("BLK", "BlackRock", "Finance"),
    ("AXP", "American Express", "Finance"),
    ("V", "Visa", "Finance"),
    ("MA", "Mastercard", "Finance"),
    ("PYPL", "PayPal", "Finance"),
    ("C", "Citigroup", "Finance"),
    ("SCHW", "Charles Schwab", "Finance"),
    ("USB", "US Bancorp", "Finance"),
    ("PNC", "PNC Financial", "Finance"),
    # Healthcare
    ("JNJ", "Johnson & Johnson", "Healthcare"),
    ("UNH", "UnitedHealth", "Healthcare"),
    ("PFE", "Pfizer", "Healthcare"),
    ("ABBV", "AbbVie", "Healthcare"),
    ("MRK", "Merck", "Healthcare"),
    ("TMO", "Thermo Fisher", "Healthcare"),
    ("ABT", "Abbott", "Healthcare"),
    ("LLY", "Eli Lilly", "Healthcare"),
    ("AMGN", "Amgen", "Healthcare"),
    ("GILD", "Gilead", "Healthcare"),
    ("CVS", "CVS Health", "Healthcare"),
    ("BMY", "Bristol-Myers Squibb", "Healthcare"),
    ("DHR", "Danaher", "Healthcare"),
    ("CI", "Cigna", "Healthcare"),
    # Consumer
    ("WMT", "Walmart", "Consumer"),
    ("HD", "Home Depot", "Consumer"),
    ("PG", "Procter & Gamble", "Consumer"),
    ("KO", "Coca-Cola", "Consumer"),
    ("PEP", "PepsiCo", "Consumer"),
    ("MCD", "McDonald's", "Consumer"),
    ("COST", "Costco", "Consumer"),
    ("NKE", "Nike", "Consumer"),
    ("SBUX", "Starbucks", "Consumer"),
    ("TGT", "Target", "Consumer"),
    ("LOW", "Lowe's", "Consumer"),
    ("DIS", "Disney", "Consumer"),
    ("NFLX", "Netflix", "Consumer"),
    ("TJX", "TJ Maxx", "Consumer"),
    ("CMG", "Chipotle", "Consumer"),
    # Energy
    ("XOM", "ExxonMobil", "Energy"),
    ("CVX", "Chevron", "Energy"),
    ("COP", "ConocoPhillips", "Energy"),
    ("SLB", "Schlumberger", "Energy"),
    ("EOG", "EOG Resources", "Energy"),
    ("MPC", "Marathon Petroleum", "Energy"),
    ("PSX", "Phillips 66", "Energy"),
    ("VLO", "Valero", "Energy"),
    ("OXY", "Occidental", "Energy"),
    ("KMI", "Kinder Morgan", "Energy"),
    # Industrial
    ("CAT", "Caterpillar", "Industrial"),
    ("DE", "Deere & Company", "Industrial"),
    ("BA", "Boeing", "Industrial"),
    ("HON", "Honeywell", "Industrial"),
    ("RTX", "Raytheon", "Industrial"),
    ("LMT", "Lockheed Martin", "Industrial"),
    ("GE", "GE Aerospace", "Industrial"),
    ("MMM", "3M", "Industrial"),
    ("UPS", "UPS", "Industrial"),
    ("FDX", "FedEx", "Industrial"),
    ("EMR", "Emerson", "Industrial"),
    ("ITW", "Illinois Tool Works", "Industrial"),
    # Communication
    ("T", "AT&T", "Communication"),
    ("VZ", "Verizon", "Communication"),
    ("CMCSA", "Comcast", "Communication"),
    ("TMUS", "T-Mobile", "Communication"),
    # Utilities & Real Estate
    ("NEE", "NextEra Energy", "Utilities"),
    ("DUK", "Duke Energy", "Utilities"),
    ("SO", "Southern Company", "Utilities"),
    ("AMT", "American Tower", "Real Estate"),
    ("PLD", "Prologis", "Real Estate"),
    ("CCI", "Crown Castle", "Real Estate"),
    # Materials
    ("LIN", "Linde", "Materials"),
    ("APD", "Air Products", "Materials"),
    ("ECL", "Ecolab", "Materials"),
    ("NEM", "Newmont", "Materials"),
    ("FCX", "Freeport-McMoRan", "Materials"),
]

db = Database()
for ticker, name, sector in stocks:
    db.insert_stock(ticker, name, sector)
db.close()

print(f"Database initialized with {len(stocks)} stocks.")
