from src.database import Database

stocks = [
    # Technology
    ("AAPL", "Apple", "Technology"),
    ("MSFT", "Microsoft", "Technology"),
    ("GOOGL", "Alphabet", "Technology"),
    ("AMZN", "Amazon", "Technology"),
    ("NVDA", "NVIDIA", "Technology"),
    ("META", "Meta", "Technology"),
    ("TSLA", "Tesla", "Technology"),
    ("AVGO", "Broadcom", "Technology"),
    ("ORCL", "Oracle", "Technology"),
    ("CSCO", "Cisco", "Technology"),
    ("INTC", "Intel", "Technology"),
    ("AMD", "AMD", "Technology"),
    ("ADBE", "Adobe", "Technology"),
    ("CRM", "Salesforce", "Technology"),
    ("QCOM", "Qualcomm", "Technology"),
    ("TXN", "Texas Instruments", "Technology"),
    ("IBM", "IBM", "Technology"),
    ("NOW", "ServiceNow", "Technology"),
    ("INTU", "Intuit", "Technology"),
    ("AMAT", "Applied Materials", "Technology"),
    # Finance
    ("JPM", "JPMorgan Chase", "Finance"),
    ("BAC", "Bank of America", "Finance"),
    ("WFC", "Wells Fargo", "Finance"),
    ("GS", "Goldman Sachs", "Finance"),
    ("MS", "Morgan Stanley", "Finance"),
    ("BLK", "BlackRock", "Finance"),
    ("AXP", "American Express", "Finance"),
    ("V", "Visa", "Finance"),
    ("MA", "Mastercard", "Finance"),
    ("PYPL", "PayPal", "Finance"),
    ("C", "Citigroup", "Finance"),
    ("SCHW", "Charles Schwab", "Finance"),
    ("USB", "US Bancorp", "Finance"),
    ("PNC", "PNC Financial", "Finance"),
    # Healthcare
    ("JNJ", "Johnson & Johnson", "Healthcare"),
    ("UNH", "UnitedHealth", "Healthcare"),
    ("PFE", "Pfizer", "Healthcare"),
    ("ABBV", "AbbVie", "Healthcare"),
    ("MRK", "Merck", "Healthcare"),
    ("TMO", "Thermo Fisher", "Healthcare"),
    ("ABT", "Abbott", "Healthcare"),
    ("LLY", "Eli Lilly", "Healthcare"),
    ("AMGN", "Amgen", "Healthcare"),
    ("GILD", "Gilead", "Healthcare"),
    ("CVS", "CVS Health", "Healthcare"),
    ("BMY", "Bristol-Myers Squibb", "Healthcare"),
    ("DHR", "Danaher", "Healthcare"),
    ("CI", "Cigna", "Healthcare"),
    # Consumer
    ("WMT", "Walmart", "Consumer"),
    ("HD", "Home Depot", "Consumer"),
    ("PG", "Procter & Gamble", "Consumer"),
    ("KO", "Coca-Cola", "Consumer"),
    ("PEP", "PepsiCo", "Consumer"),
    ("MCD", "McDonald's", "Consumer"),
    ("COST", "Costco", "Consumer"),
    ("NKE", "Nike", "Consumer"),
    ("SBUX", "Starbucks", "Consumer"),
    ("TGT", "Target", "Consumer"),
    ("LOW", "Lowe's", "Consumer"),
    ("DIS", "Disney", "Consumer"),
    ("NFLX", "Netflix", "Consumer"),
    ("TJX", "TJ Maxx", "Consumer"),
    ("CMG", "Chipotle", "Consumer"),
    # Energy
    ("XOM", "ExxonMobil", "Energy"),
    ("CVX", "Chevron", "Energy"),
    ("COP", "ConocoPhillips", "Energy"),
    ("SLB", "Schlumberger", "Energy"),
    ("EOG", "EOG Resources", "Energy"),
    ("MPC", "Marathon Petroleum", "Energy"),
    ("PSX", "Phillips 66", "Energy"),
    ("VLO", "Valero", "Energy"),
    ("OXY", "Occidental", "Energy"),
    ("KMI", "Kinder Morgan", "Energy"),
    # Industrial
    ("CAT", "Caterpillar", "Industrial"),
    ("DE", "Deere & Company", "Industrial"),
    ("BA", "Boeing", "Industrial"),
    ("HON", "Honeywell", "Industrial"),
    ("RTX", "Raytheon", "Industrial"),
    ("LMT", "Lockheed Martin", "Industrial"),
    ("GE", "GE Aerospace", "Industrial"),
    ("MMM", "3M", "Industrial"),
    ("UPS", "UPS", "Industrial"),
    ("FDX", "FedEx", "Industrial"),
    ("EMR", "Emerson", "Industrial"),
    ("ITW", "Illinois Tool Works", "Industrial"),
    # Communication
    ("T", "AT&T", "Communication"),
    ("VZ", "Verizon", "Communication"),
    ("CMCSA", "Comcast", "Communication"),
    ("TMUS", "T-Mobile", "Communication"),
    # Utilities & Real Estate
    ("NEE", "NextEra Energy", "Utilities"),
    ("DUK", "Duke Energy", "Utilities"),
    ("SO", "Southern Company", "Utilities"),
    ("AMT", "American Tower", "Real Estate"),
    ("PLD", "Prologis", "Real Estate"),
    ("CCI", "Crown Castle", "Real Estate"),
    # Materials
    ("LIN", "Linde", "Materials"),
    ("APD", "Air Products", "Materials"),
    ("ECL", "Ecolab", "Materials"),
    ("NEM", "Newmont", "Materials"),
    ("FCX", "Freeport-McMoRan", "Materials"),
]

etfs = [
    # Broad US Equity
    ("SPY",  "SPDR S&P 500 ETF",               "ETF - US Equity"),
    ("VOO",  "Vanguard S&P 500 ETF",            "ETF - US Equity"),
    ("IVV",  "iShares Core S&P 500 ETF",        "ETF - US Equity"),
    ("QQQ",  "Invesco QQQ NASDAQ-100 ETF",       "ETF - US Equity"),
    ("VTI",  "Vanguard Total Stock Market ETF",  "ETF - US Equity"),
    ("IWM",  "iShares Russell 2000 ETF",         "ETF - US Equity"),
    ("VUG",  "Vanguard Growth ETF",              "ETF - US Equity"),
    ("VTV",  "Vanguard Value ETF",               "ETF - US Equity"),
    ("RSP",  "Invesco S&P 500 Equal Weight ETF", "ETF - US Equity"),
    # International
    ("EFA",  "iShares MSCI EAFE ETF",            "ETF - International"),
    ("VWO",  "Vanguard Emerging Markets ETF",    "ETF - International"),
    ("VXUS", "Vanguard Total International ETF", "ETF - International"),
    ("VEA",  "Vanguard Developed Markets ETF",   "ETF - International"),
    ("EEM",  "iShares MSCI Emerging Markets ETF","ETF - International"),
    # Sector
    ("XLK",  "Technology Select Sector SPDR",    "ETF - Sector"),
    ("XLF",  "Financial Select Sector SPDR",     "ETF - Sector"),
    ("XLV",  "Health Care Select Sector SPDR",   "ETF - Sector"),
    ("XLE",  "Energy Select Sector SPDR",        "ETF - Sector"),
    ("XLI",  "Industrial Select Sector SPDR",    "ETF - Sector"),
    ("XLY",  "Consumer Discretionary SPDR",      "ETF - Sector"),
    ("XLRE", "Real Estate Select Sector SPDR",   "ETF - Sector"),
    ("XLP",  "Consumer Staples Select Sector SPDR","ETF - Sector"),
    ("SOXX", "iShares Semiconductor ETF",        "ETF - Sector"),
    # Bonds
    ("BND",  "Vanguard Total Bond Market ETF",   "ETF - Bonds"),
    ("AGG",  "iShares Core US Aggregate Bond ETF","ETF - Bonds"),
    ("TLT",  "iShares 20+ Year Treasury Bond ETF","ETF - Bonds"),
    ("SHY",  "iShares 1-3 Year Treasury Bond ETF","ETF - Bonds"),
    ("HYG",  "iShares High Yield Corporate Bond ETF","ETF - Bonds"),
    ("LQD",  "iShares Investment Grade Corporate ETF","ETF - Bonds"),
    # Dividend
    ("VYM",  "Vanguard High Dividend Yield ETF", "ETF - Dividend"),
    ("SCHD", "Schwab US Dividend Equity ETF",    "ETF - Dividend"),
    ("DVY",  "iShares Select Dividend ETF",      "ETF - Dividend"),
    # Commodities & Real Assets
    ("GLD",  "SPDR Gold Trust ETF",              "ETF - Commodities"),
    ("SLV",  "iShares Silver Trust ETF",         "ETF - Commodities"),
    ("VNQ",  "Vanguard Real Estate ETF",         "ETF - Real Estate"),
    # Thematic
    ("ARKK", "ARK Innovation ETF",               "ETF - Thematic"),
    ("ICLN", "iShares Global Clean Energy ETF",  "ETF - Thematic"),
]

db = Database()
for ticker, name, sector in stocks:
    db.insert_stock(ticker, name, sector)
for ticker, name, sector in etfs:
    db.insert_stock(ticker, name, sector)
db.close()

print(f"Database initialized with {len(stocks)} stocks and {len(etfs)} ETFs.")
